name: Build Vulktool APK
on: [push]

env:
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
  ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
  PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
  BUILDOZER_ALLOW_ROOT: 1

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install system dependencies & fix libtinfo compat
        run: |
          sudo sed -i "s@http://.*archive.ubuntu.com@https://mirrors.aliyun.com@g" /etc/apt/sources.list
          sudo sed -i "s@http://.*security.ubuntu.com@https://mirrors.aliyun.com@g" /etc/apt/sources.list
          sudo apt update -y
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config libpng-dev libssl-dev python3-venv zlib1g-dev libncurses5-dev cmake libffi-dev
          sudo ln -sf /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5
          sudo ldconfig

      - name: Install python dependencies
        run: pip3 install buildozer cython pycryptodome --disable-pip-version-check

      - name: Run encrypt script
        run: python3 encrypt.py

      - name: Write SDK license file to avoid manual agreement
        run: |
          mkdir -p ~/.android
          echo "24333f8a63b6825ea99c7ed4482df2b65d1a094da" > ~/.android/repositories.cfg

      - name: Compile APK
        run: buildozer android debug <<< $'\n\n\n'

      - name: Upload APK file
        uses: actions/upload-artifact@v4
        with:
          name: Output-APK
          path: bin/*.apk
          retention-days: 30
