name: Build Vulktool APK
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装编译依赖
        run: |
          sudo apt update -y
          sudo apt install git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config libpng-dev libssl-dev python3-venv -y
          pip3 install buildozer
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - name: 运行原版加密脚本encrypt.py
        run: python3 encrypt.py
      - name: 依据原始buildozer.spec执行APK打包
        run: buildozer android debug
      - name: 导出成品APK
        uses: actions/upload-artifact@v4
        with:
          name: 成品安卓APK压缩包
          path: bin/*.apk

